### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by mattish91**
as you can see, github have changed the access url from github.com to githubusercontent.com and this needs to be done accordingly.

### CODE REVIEW

**Comment by corbindavenport** [comment]
Are you sure? I get a 404 error on usercontent: https://githubusercontent.com/corbindavenport/nexus-tools/raw/master/bin/linux-i386-adb

But the old link works just fine: https://github.com/corbindavenport/nexus-tools/raw/master/bin/linux-i386-adb

**Comment by mattish91** [comment]
Well, for me that was the only way it worked, otherwise it didn't download anything (Neverware Cloudready) not sure if that has to do with anything tho. I could fresh install tomorrow and report back and see if my current fork works and report back. 

(I checked for similar issues on google, and best answer was to use githubusercontent.com instead, and it worked out just fine for me yesterday night.) had to modify the way i grabbed your script as well in order to get anything.

But like i stated above, ill try to fresh install Cloudready tomorrow and report back my result including logs and such.

**Comment by mattish91** [comment]
So, after fiddeling around abit in chrome os i constantly break it and remembered to take some screenshots and actually wrote a post about how i did it in the first place also aded a image from my device output. Here it is: https://forums.mspot.nu/viewtopic.php?f=5&t=8 hope you ejoy reading it along with the following article, maybe you could do your script more automatic with this info? Thanks for sharing your awesome project!

**Comment by corbindavenport** [comment]
I remember doing this years ago, but now you can run Nexus Tools in the Linux subsystem: https://www.androidpolice.com/2018/08/19/install-linux-applications-chrome-os/

Is the subsystem not available in Neverware?

**Comment by mattish91** [comment]
Well yes it is tho ^^ but i can't start it on my old hardware without the computer resetting it self ^^ so this came up ^^

**Pull request closed without merging**
